export const directEnv: Record<string, string> = {
  APPSHEET_ACCESS_KEY: "",
  APPSHEET_APP_ID: "",
  APPSHEET_TABLE_NAME: "",
  GOOGLE_PRIVATE_KEY: "",
  GOOGLE_SERVICE_ACCOUNT_EMAIL: "",
  GOOGLE_SHEETS_SHEET_NAME: "",
  GOOGLE_SHEETS_SPREADSHEET_ID: "",
  SIDJILCOM_ADMIN_KEY: "",
  SIDJILCOM_COOKIE: "",
  SIDJILCOM_P_AUTH: "",
};
